import { type AppType } from "next/app";

import { ThemeProvider } from "@material-tailwind/react";

import { api } from "~/utils/api";

import "../styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClerkProvider {...pageProps} >
        <ThemeProvider>
        <Component {...pageProps} />;
        </ThemeProvider>
      </ClerkProvider>
    </>
  )
};

export default api.withTRPC(MyApp);
